import { ApplicationConfig, provideZonelessChangeDetection, importProvidersFrom, LOCALE_ID, DEFAULT_CURRENCY_CODE } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { authInterceptor } from '../../libs/core/auth/auth.interceptor';
import { apiInterceptor } from '../../libs/core/api/api.interceptor';
import { cacheInterceptor } from '../../libs/core/cache/cache.interceptor';
import { registerLocaleData } from '@angular/common';
import localeEs from '@angular/common/locales/es';

registerLocaleData(localeEs);

import localeEsAr from '@angular/common/locales/es-AR';
registerLocaleData(localeEsAr);

import {
  LucideAngularModule,
  LayoutDashboard,
  FileText,
  User,
  Grid,
  Printer,
  Layers,
  BarChart3,
  Settings,
  ChevronLeft,
  ChevronRight,
  Package,
  ShoppingCart,
  Zap,
  Clock,
  Briefcase,
  Users,
  Hammer,
  LogOut,
  Menu,
  Bell,
  Sun,
  Moon,
  Plus,
  Monitor,
  Trash2,
  X,
  Activity,
  UserCog,
  UserCheck,
  UserX,
  Database,
  Pin,
  PinOff,
  Search,
  Cpu,
  Box,
  ClipboardList,
  Trees,
  HardHat,
  PackageSearch,
  Landmark,
  Globe,
  Save,
  Wallet,
  Store,
  Minus,
  Lock,
  Unlock,
  History,
  TrendingUp,
  Edit2,
  Banknote,
  CheckCircle2,
  AlertCircle,
  AlertTriangle,
  Info,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Building,
  Building2,
  Calendar,
  ChevronDown,
  CreditCard,
  DollarSign,
  LayoutGrid,
  Loader2,
  Pause,
  Play,
  RefreshCw,
  ShieldAlert,
  Slash,
  Terminal,
  Truck,
  Mail,
  MailQuestion,
  Shield,
  ShoppingBag,
  Receipt
} from 'lucide-angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([cacheInterceptor, apiInterceptor, authInterceptor])),
    { provide: LOCALE_ID, useValue: 'es-AR' },
    { provide: DEFAULT_CURRENCY_CODE, useValue: 'ARS' },
    importProvidersFrom(
      LucideAngularModule.pick({
        LayoutDashboard,
        FileText,
        User,
        Grid,
        Printer,
        Layers,
        BarChart3,
        Settings,
        ChevronLeft,
        ChevronRight,
        Package,
        ShoppingCart,
        Zap,
        Clock,
        Briefcase,
        Users,
        Hammer,
        LogOut,
        Menu,
        Bell,
        Sun,
        Moon,
        ChevronDown,
        Building2,
        Plus,
        Monitor,
        Trash2,
        X,
        Activity,
        UserCog,
        UserCheck,
        UserX,
        Database,
        Pin,
        PinOff,
        Search,
        Cpu,
        Box,
        ClipboardList,
        Trees,
        HardHat,
        PackageSearch,
        Landmark,
        Globe,
        Save,
        Wallet,
        Store,
        Minus,
        Lock,
        Unlock,
        History,
        TrendingUp,
        Edit2,
        CreditCard,
        Banknote,
        CheckCircle2,
        AlertCircle,
        AlertTriangle,
        Info,
        ArrowLeft,
        ArrowRight,
        ArrowUpRight,
        Building,
        Calendar,
        DollarSign,
        LayoutGrid,
        Loader2,
        Pause,
        Play,
        RefreshCw,
        ShieldAlert,
        Slash,
        Terminal,
        Truck,
        Mail,
        MailQuestion,
        Shield,
        ShoppingBag,
        Receipt
      })
    )
  ]
};
